module.exports = {
    api: {
        upload: "/api/common/?act=upload",
        adminLogin: "/api/common/?act=adminLogin",
        schoolLogin: "/api/common/?act=schoolLogin",
        schoolRegister: "/api/common/?act=schoolRegister",
        speakerLogin: "/api/common/?act=speakerLogin",
        speakerRegister: "/api/common/?act=speakerRegister",
        logout: "/api/common/?act=logout",
        // 密码重置
        resetPassword: "/api/common/?act=resetPassword",
        // 发送短信验证码
        sendVerifyCode: "/api/common/?act=sendVerifyCode",
    },
    status: {
        // 系统级
        0: '系统未知错误',
        1: '处理正常结束',
        1: '处理正常结束',
        // 代码功能Code
        101: '未知的action',
        102: '处理正常结束',
        103: '加密通讯验证失败',
        104: '会话session不匹配',
        105: '会话session过期',
        106: '数据被锁定（并发处理）',
        107: '上传失败',
        108: '上传文件类型不支持',
        109: '上传文件太大',
        // 业务级
        201: '应用不存在',
        202: '用户不存在',
        203: '用户已存在',
        204: '登录token不匹配',
        205: '用户名校验失败（长度、字符要求等）',
        206: '密码校验失败（长度、字符要求等）',
        207: '密码不匹配（提供的密码和用户的密码不一致）',
        208: '短信验证码不一致',
        209: '手机号格式不正确',
        210: '手机号已被使用',
        211: '用户被冻结',
        212: '学校或演讲者认证状态未通过',
        213: '学校课程数量不足',
        214: '邀约不存在',
        215: '邀约与用户无关联（不是演讲者或者学校任一方）',
        216: '邀约状态不正确',
        217: '不是邀约发起者',
        218: '不是受邀请者',
        219: '邀约学校进度状态不正确',
        220: '缺少反馈',
        221: '邀约反馈不存在',
        222: '学校不存在',
    }
}
